- name: Copy Logstash Configuration
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart Logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted

- name: Check Logstash is started or not
  ansible.builtin.shell: sleep 240 ; netstat -lntp | grep 5044