- name: Update Prometheus Configuration
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Update Alerts Configuration
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /opt/prometheus/{{ item }}
  loop: "{{ alert_files }}"


- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Check Prometheus is started
  ansible.builtin.shell: netstat -lntp | grep 9090

- name: Update AlertManager Configuration
  ansible.builtin.template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart alertmanager
  ansible.builtin.systemd:
    name: alertmanager
    state: restarted

- name: Check alertmanager is started
  ansible.builtin.shell: netstat -lntp | grep 9093